import Head from 'next/head'
import styled from 'styled-components'
import Nav from '../components/Nav'
import Buttons from '../components/Buttons'
import axios from 'axios'
import Loading from '../components/Loading'
import { useEffect, useState } from 'react'

export default function Home() {

    const [random, setRandom] = useState([])
    const [loading, setLoading] = useState(true)
    const urlRandom = "https://www.thecocktaildb.com/api/json/v1/1/random.php"

    useEffect(() => {
        async function fetchData() {
          const randomCocktail = await axios.get(urlRandom)
          setRandom(randomCocktail.data.drinks[0].idDrink)
          setLoading(false)
          return randomCocktail;
        }
        fetchData();
      }, [urlRandom])

  return (
    <>
      {loading ?
        <Loading/>
      :
      <Container>
        <Head>
          <title>5 Cocktails</title>
          <meta name="description" content="Generated by Petar Jurić" />
        </Head>
        <Nav/>
        <Landing>
          <h1>5 Cocktails</h1>
          <p> 
            Find out how to mix up your next party drink for every
            situation. Serve these fan-favourite cocktails at 
            your next party. See our best ever classic cocktails, 
            including alcoholic, non-alcoholic, ordinary drinks, cocktails... <br/>
            Over hundreds of delicious cocktails and other types of party drinks and
            their recipes from open source database which is updated thanks to 
            professional bartenders and other people from around the world.
          </p>
          <Buttons lucky={random} second="true"/>
        </Landing>
      </Container>
      }
    </>
  )
}

const Container = styled.div`
  width: 100vw;
  height: 100vh;
  background: url("./images/background.jpg");
  background-position: center;
  background-size: cover;

  @media screen and (max-width: 800px) {
    background-position: left;
    background-size: cover;
  }
`

const Landing = styled.div`
  padding: 50px;
  width: 40%;
  height: auto;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding-top: 9%;

  @media screen and (max-width: 800px) {
        width: auto;
        justify-content: center;
        align-items: center;
        text-align: center;

        h1{
          font-size: 40px;
        }

        p{
          font-size: 15px;
        }
  }

  h1{
    color: #5C7441;
    font-size: 50px;
    font-weight: 800;
  }

  p{
    font-size: 20px;
    font-weight: 550;
    line-height: 25px;
    letter-spacing: .03em;
  }
`